# -----------------------------------------------------------------------
# Pre‑commit configuration for AI‑memory‑
# Runs static checks *before* code lands in CI or hits main branch.
#   • ruff   – style, bugs, autofix (equivalent to black+flake8)
#   • mypy   – strict type‑checking
#   • bandit – security linter
#   • check-yaml – validates YAML syntax (specifically `logging.yaml`)
# -----------------------------------------------------------------------
# Enable pre-commit.ci bot in PRs by default
ci: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        name: ruff (lint+format)
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: mypy (strict)
        args: ["--strict"]
        additional_dependencies: [
          "types-PyYAML>=6.0.13",
          "types-python-dateutil",
        ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        name: bandit (security scan)
        args: ["-r", "."]
        exclude: "tests|docs"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        name: check-yaml (validate logging.yaml)
        files: "logging.yaml"
